[package]
name = "basic_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }